# Lebih besar ( > )
print("1 > 1 =", 1 > 1)
# Lebih kecil ( < )
print("1 < 2 =", 1 < 2)
# Sama dengan ( == )
print("1 == 1 =", 1 == 1)
print("1 == \"1\" =", 1 == "1")
# Tidak sama dengan ( != )
print("1 != 1 =", 1 != 1)
# Lebih besar sama dengan ( >= )
print("1 >= 1 =", 1 >= 1)
# Lebih kecil sama dengan ( <= )
print("1 <= 1 =", 1 <= 1)
